[package]
name = "pyext-myrustlib"
version = "0.1.0"
authors = ["Robert Dempsey <robertonrails@gmail.com>"]
edition = "2018"

[lib]
name = "myrustlib"
crate-type = ["cdylib"]

[dependencies.cpython]
version = "0.2"
features = ["extension-module"]